// @ts-check
import { defineConfig, fontProviders } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import tailwindcss from "@tailwindcss/vite";

// Resolved at build time so the deploy's real origin flows into every absolute
// URL (canonical, hreflang, OG/Twitter image, sitemap, robots). On Cloudflare
// Pages set SITE_URL (Production env) to your custom domain; preview deploys
// fall back to Cloudflare's per-deploy CF_PAGES_URL automatically.
const SITE = process.env.SITE_URL ?? process.env.CF_PAGES_URL ?? "http://localhost:4321";

export default defineConfig({
  site: SITE,
  trailingSlash: "always",
  i18n: {
    locales: ["en", "th"],
    defaultLocale: "en",
    routing: {
      prefixDefaultLocale: false,
    },
  },
  integrations: [
    mdx(),
    sitemap({
      // Emits <xhtml:link rel="alternate" hreflang> entries per URL so search
      // engines pair the EN/TH versions. Values are the hreflang codes, kept
      // language-only to match the in-page <link hreflang> (see lib/seo.ts) and
      // <html lang>. The content is not region-specific, so no en-US/th-TH.
      i18n: {
        defaultLocale: "en",
        locales: { en: "en", th: "th" },
      },
    }),
  ],
  // Astro 6 Fonts API (stable): fonts are subset + self-hosted at build time.
  // display: "swap" so the real (branded) font always renders once loaded. The
  // shift that swap normally causes is cancelled by the metric-adjusted Latin
  // fallbacks in src/styles/font-fallbacks.css (generated by capsize): the
  // fallback occupies the same space as the real font, so the swap reflows
  // nothing. Above-the-fold faces are preloaded in BaseLayout. Net: branded
  // font always + zero layout shift — the next/font approach.
  // Astro names each generated @font-face with a hashed family (e.g.
  // "IBM Plex Sans Thai-<hash>") and exposes it via the cssVariable. Because a
  // cross-family fallback by *plain* name ("IBM Plex Sans Thai") would not
  // match that hashed face, we disable the per-family fallback chain here and
  // compose the real multi-script stack ourselves in global.css, where the
  // Thai face is referenced by its variable and a single generic ends the list.
  fonts: [
    {
      provider: fontProviders.fontsource(),
      display: "swap",
      name: "Space Grotesk",
      cssVariable: "--font-space-grotesk",
      weights: ["300 700"],
      styles: ["normal"],
      fallbacks: [],
    },
    {
      provider: fontProviders.fontsource(),
      display: "swap",
      name: "IBM Plex Sans",
      cssVariable: "--font-ibm-plex-sans",
      weights: [400, 500, 600],
      styles: ["normal"],
      fallbacks: [],
    },
    {
      provider: fontProviders.fontsource(),
      display: "swap",
      name: "IBM Plex Sans Thai",
      cssVariable: "--font-ibm-plex-sans-thai",
      weights: [400, 500, 600],
      styles: ["normal"],
      // Thai glyphs only — Latin in the /th content is served by IBM Plex Sans.
      subsets: ["thai"],
      fallbacks: [],
    },
    {
      provider: fontProviders.fontsource(),
      display: "swap",
      name: "IBM Plex Mono",
      cssVariable: "--font-ibm-plex-mono",
      weights: [400, 500],
      styles: ["normal"],
      fallbacks: [],
    },
  ],
  vite: {
    plugins: [tailwindcss()],
  },
});
